# Generated by Django 5.0 on 2024-09-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_course_grade_book_attribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(default="Default Team", max_length=250),
            preserve_default=False,
        ),
    ]
