# Generated by Django 5.0 on 2024-10-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_coursemember_name_coursemember_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="managed",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Denotes that an attribute is managed manually. Students do not self-report this data, nor is it editable to the instructor in the same ways that a normal attribute would be.",
            ),
        ),
    ]
