# Generated by Django 5.0 on 2024-10-05 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_attribute_manage_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="grade_book_attribute",
        ),
        migrations.AlterField(
            model_name="attribute",
            name="question",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.organization"
            ),
        ),
    ]
