# Generated by Django 5.0 on 2024-10-20 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_course_grade_book_attribute_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("question", models.TextField(blank=True)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("String", "String"),
                            ("Number", "Number"),
                            ("TeamTemplateSlug", "TeamTemplateSlug"),
                        ],
                        max_length=50,
                    ),
                ),
                ("max_selections", models.IntegerField()),
                (
                    "manage_type",
                    models.CharField(
                        choices=[("UserManaged", "UserManaged"), ("Grade", "Grade")],
                        max_length=50,
                    ),
                ),
                (
                    "team_set_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.teamsettemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
