services:
    nginx:
        image: nginx:latest
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./logs/nginx:/var/log/nginx/
            - ./staticfiles:/static
        depends_on:
            - web
        ports:
            - 8002:8000
        restart: always
    web:
        build: .
        image: teamable:latest
        volumes:
            - ./staticfiles:/code/staticfiles
        env_file:
            - ./.env
            - ./db.env
        depends_on:
            - db
        command: ["./runserver.sh"]
        privileged: true
        restart: always
    db:
        image: postgres:latest
        env_file: ./db.env
        volumes:
            - ./srv/postgres-data:/var/lib/postgresql/data/
        privileged: true
        restart: always
