# Generated by Django 5.0 on 2024-02-13 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "timestampedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.timestampedmodel",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("S", "Student"), ("I", "Instructor"), ("T", "TA")],
                        max_length=1,
                    ),
                ),
                ("lms_id", models.CharField(blank=True, max_length=100)),
                (
                    "course_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
                ("sections", models.ManyToManyField(to="app.section")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("app.timestampedmodel",),
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "timestampedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.timestampedmodel",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("F", "friend"), ("E", "enemy")], max_length=1
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="app.enrollment",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.enrollment"
                    ),
                ),
            ],
            options={
                "unique_together": {("from_user", "to_user")},
            },
            bases=("app.timestampedmodel",),
        ),
    ]
