# Generated by Django 5.0 on 2024-08-05 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="grade_book_attribute",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grade_book_course",
                to="app.attribute",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="team_set_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.teamsettemplate",
            ),
        ),
        migrations.AlterField(
            model_name="coursemember",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_members",
                to="app.course",
            ),
        ),
    ]
