# Generated by Django 5.0 on 2024-02-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_course_options_alter_section_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="lms_system",
        ),
        migrations.RemoveField(
            model_name="coursemember",
            name="external_lms_id",
        ),
        migrations.AlterField(
            model_name="coursemember",
            name="role",
            field=models.CharField(
                choices=[("Student", "Student"), ("Instructor", "Instructor")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="type",
            field=models.CharField(
                choices=[("Friend", "Friend"), ("Enemy", "Enemy")], max_length=10
            ),
        ),
    ]
