# Generated by Django 5.0 on 2024-03-07 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_attribute_team_set_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("endpoint", models.TextField()),
                ("http_method", models.CharField(max_length=50)),
                (
                    "use_case",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal"),
                            ("Internal Demo", "Internal Demo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("api_version", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="APILogGenerate",
            fields=[
                (
                    "apilog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.apilog",
                    ),
                ),
                ("generation_configuration", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
            bases=("app.apilog",),
        ),
    ]
