# Generated by Django 5.0 on 2024-02-14 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_enrollment_relationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSet",
            fields=[
                (
                    "timestampedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.timestampedmodel",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "course_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.course",
                        verbose_name="course",
                    ),
                ),
            ],
            bases=("app.timestampedmodel",),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "timestampedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.timestampedmodel",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "project_set_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="app.projectset",
                    ),
                ),
            ],
            bases=("app.timestampedmodel",),
        ),
    ]
