# Generated by Django 5.0 on 2024-03-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_attribute_team_set_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="name",
            field=models.TextField(default="Default Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attributeoption",
            name="label",
            field=models.TextField(default="Option Title"),
            preserve_default=False,
        ),
    ]
