# Generated by Django 5.0 on 2024-07-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("app", "0004_organization_course_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursemember",
            name="lms_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="coursemember",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="lms_access_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="lms_api_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="lms_course_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="lms_type",
            field=models.CharField(
                blank=True, choices=[("CANVAS", "Canvas")], max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coursemember",
            name="sections",
            field=models.ManyToManyField(
                blank=True, related_name="section_members", to="app.section"
            ),
        ),
        migrations.AlterField(
            model_name="coursemember",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_memberships",
                to="accounts.myuser",
            ),
        ),
    ]
