# Generated by Django 5.0 on 2024-03-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_organization_course_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teamtemplate",
            name="name",
            field=models.CharField(max_length=250),
            preserve_default=False,
        ),
    ]
