# Generated by Django 5.0 on 2024-07-06 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_coursemember_lms_id_coursemember_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamset",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_sets",
                to="app.course",
            ),
            preserve_default=False,
        ),
    ]
