# Generated by Django 5.0 on 2024-07-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_teamset_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="lms_access_token",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="lms_course_id",
        ),
        migrations.AddField(
            model_name="course",
            name="lms_access_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="lms_course_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
