# Generated by Django 5.0 on 2024-07-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_organization_lms_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="lms_opt_in_quiz_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
