# Generated by Django 5.0 on 2025-03-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canvas_oauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canvasoauth2token",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
