name: Run Tests

on: [ push ]

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ "3.11" ]

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip && python -m pip install black[jupyter]==23.12.1
            - name: Lint with Black
              run: |
                  python -m black . --check
            - uses: jakebailey/pyright-action@v2

    build:
        needs: lint
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-12 ]
                python-version: [ "3.11" ]

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v4
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip && python -m pip install -r  requirements.txt
